version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: ["npm", "run", "start:server"]
    volumes:
      - /usr/src/app
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: vendure
      DB_USERNAME: postgres
      DB_PASSWORD: password
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start:worker"]
    volumes:
      - /usr/src/app
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: vendure
      DB_USERNAME: postgres
      DB_PASSWORD: password
  database:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vendure
#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
#     container_name: elasticsearch-vendure
#     environment:
#       - discovery.type=single-node
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     volumes:
#       - esdata:/usr/share/elasticsearch/data
#     ports:
#       - 9200:9200
#     networks:
#       - esnet
# volumes:
#   esdata:
#     driver: local
# networks:
#   esnet: