# syntax=docker/dockerfile:1.7
FROM node:20-bookworm-slim

WORKDIR /usr/src/app

COPY package.json yarn.lock ./
RUN --mount=type=cache,target=/usr/local/share/.cache/yarn \
    yarn install --non-interactive

COPY . .

EXPOSE 3000 3002

CMD ["yarn", "dev"]
